version: "3.6"

services:
  ehco:
    container_name: ehco
    image: ehco1996/ehco:latest
    network_mode: host
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5k"
        max-file: "2"
    command: ["-c", ""]
